import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { setPi } from "./helpers.ts";
import lookupCharacterTool from "./state/lookup_character.ts";
import lookupRegionTool from "./lookup/lookup_region.ts";
import diceRollTool from "./lookup/dice_roll.ts";
import getStatusTool from "./state/get_status.ts";
import transferItemTool from "./action/transfer_item.ts";
import adjustRelationTool from "./state/adjust_relation.ts";
import grantSkillExpTool from "./state/grant_skill_exp.ts";
import initGameTool from "./state/init_game.ts";
import commitTurnTool from "./state/commit_turn.ts";
import setFlagsTool from "./state/set_flags.ts";
import toggleLayer1Tool from "./state/toggle_layer1.ts";
import toggleAumodeTool from "./state/toggle_aumode.ts";
import sexTouchTool from "./action/sex_touch.ts";
import masturbateTool from "./action/masturbate.ts";
import combatActionTool from "./action/combat_action.ts";
import stealItemTool from "./action/steal_item.ts";
import equipItemTool from "./action/equip_item.ts";
import useItemTool from "./action/use_item.ts";
import moveTool from "./lookup/move.ts";
import moveToTool from "./lookup/move_to.ts";
import worldInteractTool from "./action/world_interact.ts";
import settleSceneTool from "./action/settle_scene.ts";
import recordTurnLogTool from "./action/record_turn_log.ts";
import revealSecretTool from "./action/reveal_secret.ts";
import renderSceneTool from "./action/render_scene.ts";
import spawnNpcAgentTool from "./state/spawn_npc_agent.ts";
import spawnNpcAgentsTool from "./state/spawn_npc_agents.ts";
import createRoomTool from "./action/create_room.ts";
import updateReputationTool from "./state/update_reputation.ts";
import scheduleOverrideTool from "./action/schedule_override.ts";
import createCharacterTool from "./state/create_character.ts";
import setNpcOutfitTool from "./state/set_npc_outfit.ts";
import mountVehicleTool from "./action/mount_vehicle.ts";
import dismountVehicleTool from "./action/dismount_vehicle.ts";
import boardTrainTool from "./lookup/board_train.ts";
import createLocationTool from "./lookup/create_location.ts";
import buyItemTool from "./action/buy_item.ts";
import identityCheckTool from "./action/identity_check.ts";
import sellItemTool from "./action/sell_item.ts";
import monthlyGrowthTool from "./action/monthly_growth.ts";
import workJobTool from "./action/work_job.ts";
import completeTravelTool from "./lookup/complete_travel.ts";
import spawnItemTool from "./action/spawn_item.ts";
import inflictDamageTool from "./action/inflict_damage.ts";
import lookupBodyTool from "./state/lookup_body.ts";
import lookupLoreTool from "./lookup/lookup_lore.ts";
import lookupVillainTool from "./lookup/lookup_villain.ts";
import addMemoryTagTool from "./state/add_memory_tag.ts";
import setNpcDrivesTool from "./state/set_npc_drives.ts";
import setNpcRelationTool from "./state/set_npc_relation.ts";
import tableCreateTool from "./action/table_create.ts";
import tableUpdateTool from "./action/table_update.ts";
import tableDeleteTool from "./action/table_delete.ts";
import tableReadTool from "./action/table_read.ts";
import openQuestTool from "./action/open_quest.ts";
import advanceQuestTool from "./action/advance_quest.ts";
import abandonQuestTool from "./action/abandon_quest.ts";
import addToPartyTool from "./state/add_to_party.ts";
import removeFromPartyTool from "./state/remove_from_party.ts";
import checkPhoneTool from "./lookup/check_phone.ts";
import sendSmsTool from "./lookup/send_sms.ts";
import browseSnsTool from "./lookup/browse_sns.ts";
import postSnsTool from "./lookup/post_sns.ts";
import makeCallTool from "./lookup/make_call.ts";
import addCalendarEventTool from "./action/add_calendar_event.ts";
import createStoryHookTool from "./action/create_story_hook.ts";
import instantiateNpcTool from "./action/instantiate_npc.ts";
import addLifeEventTool from "./action/add_life_event.ts";
import gambleBetTool from "./action/gamble_bet.ts";
import blackMarketTradeTool from "./action/black_market_trade.ts";
import managePropertyTool from "./action/manage_property.ts";
import housingStorageTool from "./action/housing_storage.ts";
import lookupWeatherTool from "./lookup/lookup_weather.ts";
import travelIntercityTool from "./lookup/travel_intercity.ts";
import interactFurnitureTool from "./action/interact_furniture.ts";
import restockShopTool from "./action/restock_shop.ts";
import useAbilityTool from "./action/use_ability.ts";
import spawnTempNpcTool from "./action/spawn_temp_npc.ts";
import lookupAbilityTool from "./lookup/lookup_ability.ts";
import gambleCommand from "./tui/gamble.ts";
import housingCommand from "./tui/housing.ts";
import relationsCommand from "./tui/relations.ts";
import statusCommand from "./tui/status.ts";
import menuCommand from "./tui/menu.ts";
import lookCommand from "./tui/look.ts";
import partyCommand from "./tui/party.ts";
import identityCommand from "./tui/identity.ts";
import goCommand from "./tui/go.ts";
import goskipCommand from "./tui/goskip.ts";
import saveCommand from "./tui/save.ts";
import loadCommand from "./tui/load.ts";
import savesCommand from "./tui/saves.ts";
import redoCommand from "./tui/redo.ts";
import sleepCommand from "./tui/sleep.ts";
import layer1Command from "./tui/layer1.ts";
import sexCommand from "./tui/sex.ts";
import roomCommand from "./tui/room.ts";
import trainCommand from "./tui/train.ts";
import bagCommand from "./tui/bag.ts";
import questCommand from "./tui/quest.ts";
import presetCommand from "./tui/preset.ts";
import calendarCommand from "./tui/calendar.ts";
import weatherCommand from "./tui/weather.ts";
import alertsCommand from "./tui/alerts.ts";
import memoryCommand from "./tui/memory.ts";
import growthCommand from "./tui/growth.ts";
import combatCommand from "./tui/combat.ts";
import shopCommand from "./tui/shop.ts";
import scheduleCommand from "./tui/schedule.ts";
import rerollCommand from "./tui/reroll.ts";
import worldCommand from "./tui/world.ts";
import achievementsCommand from "./tui/achievements.ts";

export function registerAll(pi: ExtensionAPI) {
  setPi(pi);
  // Register Flags
  pi.registerFlag("render-model", {
    description: "渲染场景所用的模型，如 'deepseek/deepseek-v4-pro' 或 'anthropic/claude-3-5-sonnet'",
    type: "string",
  });

  // Register Tools
  pi.registerTool(lookupCharacterTool);
  pi.registerTool(lookupRegionTool);
  pi.registerTool(diceRollTool);
  pi.registerTool(getStatusTool);
  pi.registerTool(transferItemTool);
  pi.registerTool(adjustRelationTool);
  pi.registerTool(grantSkillExpTool);
  pi.registerTool(initGameTool);
  pi.registerTool(commitTurnTool);
  pi.registerTool(setFlagsTool);
  pi.registerTool(toggleLayer1Tool);
  pi.registerTool(toggleAumodeTool);
  pi.registerTool(sexTouchTool);
  pi.registerTool(masturbateTool);
  pi.registerTool(combatActionTool);
  pi.registerTool(stealItemTool);
  pi.registerTool(equipItemTool);
  pi.registerTool(useItemTool);
  pi.registerTool(moveTool);
  pi.registerTool(moveToTool);
  pi.registerTool(worldInteractTool);
  pi.registerTool(settleSceneTool);
  pi.registerTool(recordTurnLogTool);
  pi.registerTool(revealSecretTool);
  pi.registerTool(renderSceneTool);
  pi.registerTool(spawnNpcAgentTool);
  pi.registerTool(spawnNpcAgentsTool);
  pi.registerTool(createRoomTool);
  pi.registerTool(updateReputationTool);
  pi.registerTool(scheduleOverrideTool);
  pi.registerTool(createCharacterTool);
  pi.registerTool(setNpcOutfitTool);
  pi.registerTool(mountVehicleTool);
  pi.registerTool(dismountVehicleTool);
  pi.registerTool(boardTrainTool);
  pi.registerTool(createLocationTool);
  pi.registerTool(buyItemTool);
  pi.registerTool(identityCheckTool);
  pi.registerTool(sellItemTool);
  pi.registerTool(monthlyGrowthTool);
  pi.registerTool(workJobTool);
  pi.registerTool(completeTravelTool);
  pi.registerTool(spawnItemTool);
  pi.registerTool(inflictDamageTool);
  pi.registerTool(lookupBodyTool);
  pi.registerTool(lookupLoreTool);
  pi.registerTool(lookupVillainTool);
  pi.registerTool(addMemoryTagTool);
  pi.registerTool(setNpcDrivesTool);
  pi.registerTool(setNpcRelationTool);
  pi.registerTool(tableCreateTool);
  pi.registerTool(tableUpdateTool);
  pi.registerTool(tableDeleteTool);
  pi.registerTool(tableReadTool);
  pi.registerTool(openQuestTool);
  pi.registerTool(advanceQuestTool);
  pi.registerTool(abandonQuestTool);
  pi.registerTool(addToPartyTool);
  pi.registerTool(removeFromPartyTool);
  pi.registerTool(checkPhoneTool);
  pi.registerTool(sendSmsTool);
  pi.registerTool(browseSnsTool);
  pi.registerTool(postSnsTool);
  pi.registerTool(makeCallTool);
  pi.registerTool(addCalendarEventTool);
  pi.registerTool(createStoryHookTool);
  pi.registerTool(instantiateNpcTool);
  pi.registerTool(spawnTempNpcTool);
  pi.registerTool(addLifeEventTool);
  pi.registerTool(gambleBetTool);
  pi.registerTool(blackMarketTradeTool);
  pi.registerTool(managePropertyTool);
  pi.registerTool(housingStorageTool);
  pi.registerTool(lookupWeatherTool);
  pi.registerTool(travelIntercityTool);
  pi.registerTool(interactFurnitureTool);
  pi.registerTool(restockShopTool);
  pi.registerTool(useAbilityTool);
  pi.registerTool(lookupAbilityTool);

  // Register Commands
  pi.registerCommand("gamble", gambleCommand);
  pi.registerCommand("housing", housingCommand);
  pi.registerCommand("relations", relationsCommand);
  pi.registerCommand("status", statusCommand);
  pi.registerCommand("menu", menuCommand);
  pi.registerCommand("look", lookCommand);
  pi.registerCommand("party", partyCommand);
  pi.registerCommand("identity", identityCommand);
  pi.registerCommand("go", goCommand);
  pi.registerCommand("goskip", goskipCommand);
  pi.registerCommand("save", saveCommand);
  pi.registerCommand("load", loadCommand);
  pi.registerCommand("saves", savesCommand);
  pi.registerCommand("redo", redoCommand);
  pi.registerCommand("sleep", sleepCommand);
  pi.registerCommand("layer1", layer1Command);
  pi.registerCommand("sex", sexCommand);
  pi.registerCommand("room", roomCommand);
  pi.registerCommand("train", trainCommand);
  pi.registerCommand("bag", bagCommand);
  pi.registerCommand("quest", questCommand);
  pi.registerCommand("preset", presetCommand);
  pi.registerCommand("calendar", calendarCommand);
  pi.registerCommand("weather", weatherCommand);
  pi.registerCommand("alerts", alertsCommand);
  pi.registerCommand("memory", memoryCommand);
  pi.registerCommand("growth", growthCommand);
  pi.registerCommand("combat", combatCommand);
  pi.registerCommand("shop", shopCommand);
  pi.registerCommand("schedule", scheduleCommand);
  pi.registerCommand("reroll", rerollCommand);
  pi.registerCommand("world", worldCommand);
  pi.registerCommand("achievements", achievementsCommand);
  pi.registerCommand("ach", achievementsCommand);
}
